// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ticket/ticket.proto

package ticket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type TicketStatus int32

const (
	TicketStatus_TICKET_STATUS_UNSPECIFIED TicketStatus = 0
	TicketStatus_TICKET_STATUS_OPEN        TicketStatus = 1
	TicketStatus_TICKET_STATUS_IN_PROGRESS TicketStatus = 2
	TicketStatus_TICKET_STATUS_RESOLVED    TicketStatus = 3
	TicketStatus_TICKET_STATUS_CLOSED      TicketStatus = 4
)

// Enum value maps for TicketStatus.
var (
	TicketStatus_name = map[int32]string{
		0: "TICKET_STATUS_UNSPECIFIED",
		1: "TICKET_STATUS_OPEN",
		2: "TICKET_STATUS_IN_PROGRESS",
		3: "TICKET_STATUS_RESOLVED",
		4: "TICKET_STATUS_CLOSED",
	}
	TicketStatus_value = map[string]int32{
		"TICKET_STATUS_UNSPECIFIED": 0,
		"TICKET_STATUS_OPEN":        1,
		"TICKET_STATUS_IN_PROGRESS": 2,
		"TICKET_STATUS_RESOLVED":    3,
		"TICKET_STATUS_CLOSED":      4,
	}
)

func (x TicketStatus) Enum() *TicketStatus {
	p := new(TicketStatus)
	*p = x
	return p
}

func (x TicketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ticket_ticket_proto_enumTypes[0].Descriptor()
}

func (TicketStatus) Type() protoreflect.EnumType {
	return &file_proto_ticket_ticket_proto_enumTypes[0]
}

func (x TicketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketStatus.Descriptor instead.
func (TicketStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{0}
}

type TicketPriority int32

const (
	TicketPriority_TICKET_PRIORITY_UNSPECIFIED TicketPriority = 0
	TicketPriority_TICKET_PRIORITY_LOW         TicketPriority = 1
	TicketPriority_TICKET_PRIORITY_MEDIUM      TicketPriority = 2
	TicketPriority_TICKET_PRIORITY_HIGH        TicketPriority = 3
	TicketPriority_TICKET_PRIORITY_CRITICAL    TicketPriority = 4
)

// Enum value maps for TicketPriority.
var (
	TicketPriority_name = map[int32]string{
		0: "TICKET_PRIORITY_UNSPECIFIED",
		1: "TICKET_PRIORITY_LOW",
		2: "TICKET_PRIORITY_MEDIUM",
		3: "TICKET_PRIORITY_HIGH",
		4: "TICKET_PRIORITY_CRITICAL",
	}
	TicketPriority_value = map[string]int32{
		"TICKET_PRIORITY_UNSPECIFIED": 0,
		"TICKET_PRIORITY_LOW":         1,
		"TICKET_PRIORITY_MEDIUM":      2,
		"TICKET_PRIORITY_HIGH":        3,
		"TICKET_PRIORITY_CRITICAL":    4,
	}
)

func (x TicketPriority) Enum() *TicketPriority {
	p := new(TicketPriority)
	*p = x
	return p
}

func (x TicketPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ticket_ticket_proto_enumTypes[1].Descriptor()
}

func (TicketPriority) Type() protoreflect.EnumType {
	return &file_proto_ticket_ticket_proto_enumTypes[1]
}

func (x TicketPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketPriority.Descriptor instead.
func (TicketPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{1}
}

// Ticket message definition
type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        TicketStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=ticket.TicketStatus" json:"status,omitempty"`
	Priority      TicketPriority         `protobuf:"varint,5,opt,name=priority,proto3,enum=ticket.TicketPriority" json:"priority,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ticket) GetStatus() TicketStatus {
	if x != nil {
		return x.Status
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket) GetPriority() TicketPriority {
	if x != nil {
		return x.Priority
	}
	return TicketPriority_TICKET_PRIORITY_UNSPECIFIED
}

func (x *Ticket) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *Ticket) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ticket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request/Response messages
type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      TicketPriority         `protobuf:"varint,3,opt,name=priority,proto3,enum=ticket.TicketPriority" json:"priority,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,4,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	ReporterId    string                 `protobuf:"bytes,6,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTicketRequest) GetPriority() TicketPriority {
	if x != nil {
		return x.Priority
	}
	return TicketPriority_TICKET_PRIORITY_UNSPECIFIED
}

func (x *CreateTicketRequest) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *CreateTicketRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketResponse) Reset() {
	*x = CreateTicketResponse{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketResponse) ProtoMessage() {}

func (x *CreateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketResponse.ProtoReflect.Descriptor instead.
func (*CreateTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *GetTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketResponse) Reset() {
	*x = GetTicketResponse{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse) ProtoMessage() {}

func (x *GetTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse.ProtoReflect.Descriptor instead.
func (*GetTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *GetTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *ListTicketsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTicketsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListTicketsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        TicketStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=ticket.TicketStatus" json:"status,omitempty"`
	Priority      TicketPriority         `protobuf:"varint,5,opt,name=priority,proto3,enum=ticket.TicketPriority" json:"priority,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTicketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTicketRequest) GetStatus() TicketStatus {
	if x != nil {
		return x.Status
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *UpdateTicketRequest) GetPriority() TicketPriority {
	if x != nil {
		return x.Priority
	}
	return TicketPriority_TICKET_PRIORITY_UNSPECIFIED
}

func (x *UpdateTicketRequest) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *UpdateTicketRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketResponse) Reset() {
	*x = UpdateTicketResponse{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketResponse) ProtoMessage() {}

func (x *UpdateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketResponse.ProtoReflect.Descriptor instead.
func (*UpdateTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type DeleteTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketRequest) Reset() {
	*x = DeleteTicketRequest{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketRequest) ProtoMessage() {}

func (x *DeleteTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketResponse) Reset() {
	*x = DeleteTicketResponse{}
	mi := &file_proto_ticket_ticket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketResponse) ProtoMessage() {}

func (x *DeleteTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketResponse.ProtoReflect.Descriptor instead.
func (*DeleteTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ticket_ticket_proto protoreflect.FileDescriptor

const file_proto_ticket_ticket_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ticket/ticket.proto\x12\x06ticket\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x02\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.ticket.TicketStatusR\x06status\x122\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x16.ticket.TicketPriorityR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\tR\n" +
	"assigneeId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb6\x01\n" +
	"\x13CreateTicketRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x122\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x16.ticket.TicketPriorityR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\x04 \x01(\tR\n" +
	"assigneeId\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\">\n" +
	"\x14CreateTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"\"\n" +
	"\x10GetTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"P\n" +
	"\x12ListTicketsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"g\n" +
	"\x13ListTicketsResponse\x12(\n" +
	"\atickets\x18\x01 \x03(\v2\x0e.ticket.TicketR\atickets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xf4\x01\n" +
	"\x13UpdateTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.ticket.TicketStatusR\x06status\x122\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x16.ticket.TicketPriorityR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\tR\n" +
	"assigneeId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\">\n" +
	"\x14UpdateTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"%\n" +
	"\x13DeleteTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteTicketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x9a\x01\n" +
	"\fTicketStatus\x12\x1d\n" +
	"\x19TICKET_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TICKET_STATUS_OPEN\x10\x01\x12\x1d\n" +
	"\x19TICKET_STATUS_IN_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16TICKET_STATUS_RESOLVED\x10\x03\x12\x18\n" +
	"\x14TICKET_STATUS_CLOSED\x10\x04*\x9e\x01\n" +
	"\x0eTicketPriority\x12\x1f\n" +
	"\x1bTICKET_PRIORITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TICKET_PRIORITY_LOW\x10\x01\x12\x1a\n" +
	"\x16TICKET_PRIORITY_MEDIUM\x10\x02\x12\x18\n" +
	"\x14TICKET_PRIORITY_HIGH\x10\x03\x12\x1c\n" +
	"\x18TICKET_PRIORITY_CRITICAL\x10\x042\xfa\x02\n" +
	"\rTicketService\x12I\n" +
	"\fCreateTicket\x12\x1b.ticket.CreateTicketRequest\x1a\x1c.ticket.CreateTicketResponse\x12@\n" +
	"\tGetTicket\x12\x18.ticket.GetTicketRequest\x1a\x19.ticket.GetTicketResponse\x12F\n" +
	"\vListTickets\x12\x1a.ticket.ListTicketsRequest\x1a\x1b.ticket.ListTicketsResponse\x12I\n" +
	"\fUpdateTicket\x12\x1b.ticket.UpdateTicketRequest\x1a\x1c.ticket.UpdateTicketResponse\x12I\n" +
	"\fDeleteTicket\x12\x1b.ticket.DeleteTicketRequest\x1a\x1c.ticket.DeleteTicketResponseB.Z,github.com/ayush-pandya/Graphql/proto/ticketb\x06proto3"

var (
	file_proto_ticket_ticket_proto_rawDescOnce sync.Once
	file_proto_ticket_ticket_proto_rawDescData []byte
)

func file_proto_ticket_ticket_proto_rawDescGZIP() []byte {
	file_proto_ticket_ticket_proto_rawDescOnce.Do(func() {
		file_proto_ticket_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ticket_ticket_proto_rawDesc), len(file_proto_ticket_ticket_proto_rawDesc)))
	})
	return file_proto_ticket_ticket_proto_rawDescData
}

var file_proto_ticket_ticket_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ticket_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_ticket_ticket_proto_goTypes = []any{
	(TicketStatus)(0),             // 0: ticket.TicketStatus
	(TicketPriority)(0),           // 1: ticket.TicketPriority
	(*Ticket)(nil),                // 2: ticket.Ticket
	(*CreateTicketRequest)(nil),   // 3: ticket.CreateTicketRequest
	(*CreateTicketResponse)(nil),  // 4: ticket.CreateTicketResponse
	(*GetTicketRequest)(nil),      // 5: ticket.GetTicketRequest
	(*GetTicketResponse)(nil),     // 6: ticket.GetTicketResponse
	(*ListTicketsRequest)(nil),    // 7: ticket.ListTicketsRequest
	(*ListTicketsResponse)(nil),   // 8: ticket.ListTicketsResponse
	(*UpdateTicketRequest)(nil),   // 9: ticket.UpdateTicketRequest
	(*UpdateTicketResponse)(nil),  // 10: ticket.UpdateTicketResponse
	(*DeleteTicketRequest)(nil),   // 11: ticket.DeleteTicketRequest
	(*DeleteTicketResponse)(nil),  // 12: ticket.DeleteTicketResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_proto_ticket_ticket_proto_depIdxs = []int32{
	0,  // 0: ticket.Ticket.status:type_name -> ticket.TicketStatus
	1,  // 1: ticket.Ticket.priority:type_name -> ticket.TicketPriority
	13, // 2: ticket.Ticket.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: ticket.Ticket.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: ticket.CreateTicketRequest.priority:type_name -> ticket.TicketPriority
	2,  // 5: ticket.CreateTicketResponse.ticket:type_name -> ticket.Ticket
	2,  // 6: ticket.GetTicketResponse.ticket:type_name -> ticket.Ticket
	2,  // 7: ticket.ListTicketsResponse.tickets:type_name -> ticket.Ticket
	0,  // 8: ticket.UpdateTicketRequest.status:type_name -> ticket.TicketStatus
	1,  // 9: ticket.UpdateTicketRequest.priority:type_name -> ticket.TicketPriority
	2,  // 10: ticket.UpdateTicketResponse.ticket:type_name -> ticket.Ticket
	3,  // 11: ticket.TicketService.CreateTicket:input_type -> ticket.CreateTicketRequest
	5,  // 12: ticket.TicketService.GetTicket:input_type -> ticket.GetTicketRequest
	7,  // 13: ticket.TicketService.ListTickets:input_type -> ticket.ListTicketsRequest
	9,  // 14: ticket.TicketService.UpdateTicket:input_type -> ticket.UpdateTicketRequest
	11, // 15: ticket.TicketService.DeleteTicket:input_type -> ticket.DeleteTicketRequest
	4,  // 16: ticket.TicketService.CreateTicket:output_type -> ticket.CreateTicketResponse
	6,  // 17: ticket.TicketService.GetTicket:output_type -> ticket.GetTicketResponse
	8,  // 18: ticket.TicketService.ListTickets:output_type -> ticket.ListTicketsResponse
	10, // 19: ticket.TicketService.UpdateTicket:output_type -> ticket.UpdateTicketResponse
	12, // 20: ticket.TicketService.DeleteTicket:output_type -> ticket.DeleteTicketResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_ticket_ticket_proto_init() }
func file_proto_ticket_ticket_proto_init() {
	if File_proto_ticket_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ticket_ticket_proto_rawDesc), len(file_proto_ticket_ticket_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ticket_ticket_proto_goTypes,
		DependencyIndexes: file_proto_ticket_ticket_proto_depIdxs,
		EnumInfos:         file_proto_ticket_ticket_proto_enumTypes,
		MessageInfos:      file_proto_ticket_ticket_proto_msgTypes,
	}.Build()
	File_proto_ticket_ticket_proto = out.File
	file_proto_ticket_ticket_proto_goTypes = nil
	file_proto_ticket_ticket_proto_depIdxs = nil
}
